changelog:
  categories:
    - title: SemVer Major
      labels:
        - ⚠️ semver/major
    - title: SemVer Minor
      labels:
        - 🆕 semver/minor
    - title: SemVer Patch
      labels:
        - 🔨 semver/patch
    - title: Other Changes
      labels:
        - semver/none
