#!/bin/bash

set -eu

swift_binary=swift

declare -a extra_args
extra_args=()

if [[ ! -z "${SWIFT_EXEC-}" ]]; then
    swift_binary="$(dirname "$SWIFT_EXEC")/swift"
elif [[ "$(uname -s)" == "Linux" ]]; then
    swift_binary=$(which swift)
fi

if [[ $# -eq 0 ]]; then
    verb=repl
    if [[ "$(uname -s)" == "Linux" ]]; then
        # to work around not being able to import Foundation in the REPL
        extra_args+="-I$(dirname "$swift_binary")/../lib/swift/clang/include/"
    fi
else
    verb="$1"
    shift
fi

openssl_libdir=""
openssl_incdir=""

export PKG_CONFIG_PATH="${PKG_CONFIG_PATH-/dev/null}:/usr/local/opt/openssl/lib/pkgconfig"
if command -v pkg-config > /dev/null; then
    pkg_config_bin="$(command -v pkg-config)"
    openssl_libdir=$("$pkg_config_bin" --libs-only-L openssl)
    openssl_incdir=$("$pkg_config_bin" --cflags openssl)
fi

if [[ ! -z "$openssl_libdir" ]]; then
    extra_args+=("-Xlinker")
    extra_args+=("$openssl_libdir")
fi
if [[ ! -z "$openssl_incdir" ]]; then
    extra_args+=("-Xcc")
    extra_args+=("$openssl_incdir")
fi

"$swift_binary" "$verb" \
    ${extra_args[@]+"${extra_args[@]}"} \
    "$@"
