//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// LengthFieldBasedFrameDecoderTest+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension LengthFieldBasedFrameDecoderTest {

   static var allTests : [(String, (LengthFieldBasedFrameDecoderTest) -> () throws -> Void)] {
      return [
                ("testFixedLengthFrameDecoderInt8", testFixedLengthFrameDecoderInt8),
                ("testFixedLengthFrameDecoderInt16", testFixedLengthFrameDecoderInt16),
                ("testFixedLengthFrameDecoderInt32", testFixedLengthFrameDecoderInt32),
                ("testFixedLengthFrameDecoderInt64", testFixedLengthFrameDecoderInt64),
                ("testFixedLengthFrameDecoderUInt8", testFixedLengthFrameDecoderUInt8),
                ("testFixedLengthFrameDecoderUInt16", testFixedLengthFrameDecoderUInt16),
                ("testFixedLengthFrameDecoderUInt32", testFixedLengthFrameDecoderUInt32),
                ("testFixedLengthFrameDecoderUInt64", testFixedLengthFrameDecoderUInt64),
           ]
   }
}

