name: 'Pull request semver label checker'
description: 'Checks that at least one semver label is applied to the pull request'
runs:
    using: "composite"
    steps:
      - name: Check labels
        run: |
            gh pr view ${{ github.event.number }} --repo apple/swift-nio --json labels \
            | jq -e '[.labels[].name] | any(. == "semver/major" or . == "semver/minor" or . == "semver/patch" or . == "semver/none")'