name: Android SDK

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      env_vars:
        type: string
        description: "Environment variables for jobs as JSON (e.g., '{\"DEBUG\":\"1\",\"LOG_LEVEL\":\"info\"}')."
        default: "{}"
      additional_command_arguments:
        type: string
        description: "Additional arguments passed to swift build (the Android SDK will be specified). Defaults to empty."
        default: ""

jobs:
  android-sdk:
    name: Android Swift SDK
    # Workaround https://github.com/nektos/act/issues/1875
    uses: apple/swift-nio/.github/workflows/swift_test_matrix.yml@android-sdk
    with:
      name: "Android Swift SDK"
      matrix_string: >-
        {
          "config":[
            {
              "name":"main Jammy",
              "swift_version":"main",
              "platform":"Linux",
              "runner":"ubuntu-latest",
              "image":"ubuntu:jammy",
              "setup_command":"apt update -q && apt install -y -q curl jq tar && curl -s --retry 3 https://raw.githubusercontent.com/apple/swift-nio/android-sdk/scripts/install_swift_prerequisites.sh | bash && curl -s --retry 3 https://raw.githubusercontent.com/apple/swift-nio/android-sdk/scripts/install_swift_sdk.sh | INSTALL_SWIFT_BRANCH=main INSTALL_SWIFT_ARCH=x86_64 INSTALL_SWIFT_SDK=android-sdk bash && hash -r",
              "command":"curl -s --retry 3 https://raw.githubusercontent.com/apple/swift-nio/android-sdk/scripts/swift-build-with-android-sdk.sh | bash -s --",
              "command_arguments":"${{ inputs.additional_command_arguments }}",
              "env":'"$env_vars_json"'
            }
          ]
        }
