name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

## We are cancelling previously triggered workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift:
        - image: swift:5.8-jammy
        - image: swift:5.9-jammy
        - image: swift:5.10-noble
        - image: swiftlang/swift:nightly-6.0-jammy
        - image: swiftlang/swift:nightly-main-jammy
    container:
      image: ${{ matrix.swift.image }}
    timeout-minutes: 20
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run tests
      run: swift test

  api-breakage:
    name: API breakage checks
    runs-on: ubuntu-latest
    container:
      image: swift:5.10-noble
    timeout-minutes: 20
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # We need to fetch everything otherwise only the head commit will be fetched.
        fetch-depth: 0
    - name: Mark the workspace as safe
      # https://github.com/actions/checkout/issues/766
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: Run API breakage check
      run: swift package diagnose-api-breaking-changes origin/main